# Generated by Django 4.2.7 on 2025-04-23 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='photo',
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incidents/photos/')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='incidents.incident')),
            ],
        ),
    ]
