# Generated by Django 4.2.7 on 2025-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incident_photo_incidentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
